### ISSUE TITLE
User profile page

### ISSUE THREAD

**Issue by davide-castro20** [FEUP-ESOF-2020-21/open-cx-t1g2-escama#17]
Create a prototype of the user profile page.

### Elements to include:

- [x] User profile avatar
- [x] Reputation score
- [x] Previously asked questions
- [x] Planned talks

**Comment by Educorreia932** [comment]
### Elements to include:
- User profile icon
- Reputation score
- Previously asked questions
- Previously attended talks
- Planned talks
