### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by davide-castro20** [FEUP-ESOF-2020-21/open-cx-t1g2-escama#20]
Ask users to log in or sign up when opening the app and log out

- [x] Login
- [x] Register
- [x] Logout

## Useful Links
[Using Firebase Authentication](https://firebase.flutter.dev/docs/auth/usage/)
[Firebase Auth Tutorial #15- Firestore Users Collection](https://www.youtube.com/watch?v=qWy9ylc3f9U)
[Flutter & Firebase authentication with streams and StreamBuilder](https://www.youtube.com/watch?v=nxu4bMpPvCQ)

**Comment by Educorreia932** [comment]
[Using Firebase Authentication](https://firebase.flutter.dev/docs/auth/usage/)

**Comment by Educorreia932** [comment]
[Firebase Auth Tutorial #15- Firestore Users Collection](https://www.youtube.com/watch?v=qWy9ylc3f9U)
